### ISSUE TITLE
DGFIP backend fails when encountering raw constants

### ISSUE THREAD

**Issue by Keryan-dev** [MLanguage/mlang#109]
Since #84 which uses `Dgfip_varid` to point at the right place in the TGV instead of on-the-fly index generation, the code generation fails on references to variables that are actually constants.

This should be expected since the compirateur inlines the constants in the code and the TGV contains only actual variables, contrarily to Mlang where the distinction is lost.
The problem resolves itself when using optimizations, that include the behavior of the compirateur in that regard. This is still a bug without it though.

A cheap solution would be to force at least one inlining pass all the time, at least for the DGFIP backend, any opinions on this ?

**Comment by ddeclerck** [comment]
My 50 cents: have a separate optimization pipeline for the DGFiP case, that mimics the original compiler optimizations.

**Comment by rmonat** [comment]
Otherwise, could we add an exception to the variable generation when the variable is a) not in the TGV and b) a constant?

**Comment by Keryan-dev** [comment]
> Otherwise, could we add an exception to the variable generation when the variable is a) not in the TGV and b) a constant?

Problem is, as of now we assumed everything was in the TGV, and Mlang completely lose the information about constants and treats them as any assigned variable. We can add the information in the variable record surely, and substitute them at some point during a transformation. Do their names appear at any point in the code generated by the compirateur ?

**Comment by ddeclerck** [comment]
> Do their names appear at any point in the code generated by the compirateur ?

It doesn't seem to be the case. Constants are simply inlined in the generated C code (take for instance constant ABAT_UNVIEUX in rule 701200 in chap-7.m). They do not even appear in the "variable dictionary" (the auxiliary files).

**Comment by Keryan-dev** [comment]
Right, so we can substitute them whenever we want in the pipeline.
