### ISSUE TITLE
Unsafe math option seems to change computation results in backends

### ISSUE THREAD

**Issue by Keryan-dev** [MLanguage/mlang#124]
`--fast-math` has shown to fail when added to optimized backend tests. I strongly suspect it shouldn't be the case as the calculette doesn't rely on technicalities of floating point implementations, meaning some simplifications allowed by this flag are incorrect.

**Comment by denismerigoux** [comment]
Here are the four optimizations triggered by `--fast-math`:

https://github.com/MLanguage/mlang/blob/537f6917142cd0b385a9d33ea74e8a0d47cbccd6/src/mlang/optimizing_ir/partial_evaluation.ml#L338-L340

https://github.com/MLanguage/mlang/blob/537f6917142cd0b385a9d33ea74e8a0d47cbccd6/src/mlang/optimizing_ir/partial_evaluation.ml#L344-L346

https://github.com/MLanguage/mlang/blob/537f6917142cd0b385a9d33ea74e8a0d47cbccd6/src/mlang/optimizing_ir/partial_evaluation.ml#L359-L361

https://github.com/MLanguage/mlang/blob/537f6917142cd0b385a9d33ea74e8a0d47cbccd6/src/mlang/optimizing_ir/partial_evaluation.ml#L362-L364

Our reference about sound and unsound float optimizations is https://xavierleroy.org/publi/floating-point-compcert.pdf#page=21.

**Comment by Keryan-dev** [comment]
Yes, I saw those and could not think of anything going wrong with it either.

To narrow the issue down, the tests failures happen on optimized backend but not on optimized interpreter. Which is a bit disturbing because I don't see how these optimisations would trigger buggy code path on the code generation side that we wouldn't see otherwise.

**Comment by Keryan-dev** [comment]
I can't seem to reproduce the issue on the current version. Closing.
