### ISSUE TITLE
Static binary compilation for older platforms

### ISSUE THREAD

**Issue by jemsab** [MLanguage/mlang#16]
In order to run the main binary on older linux platforms, the binary must be statically linked with the musl implementation of the C standard library. 

Unfortunately the gmp dependency seems to prevent such a linking to take place using an opam compiler with musl and static enabled.

Indeed `make deps` gives the following error output : 
opam install ppx_deriving ANSITerminal re ocamlgraph dune menhir \
	cmdliner dune-build-info visitors parmap num ocamlformat mlgmpidl \
	ocamlformat
[NOTE] Package ocamlformat is already installed (current version is 0.18.0).
[NOTE] Package ocamlformat is already installed (current version is 0.18.0).
[NOTE] Package num is already installed (current version is 1.4).
[NOTE] Package parmap is already installed (current version is 1.2.3).
[NOTE] Package visitors is already installed (current version is 20210608).
[NOTE] Package dune-build-info is already installed (current version is 2.9.0).
[NOTE] Package cmdliner is already installed (current version is 1.0.4).
[NOTE] Package menhir is already installed (current version is 20210419).
[NOTE] Package dune is already installed (current version is 2.9.0).
[NOTE] Package ocamlgraph is already installed (current version is 2.0.0).
[NOTE] Package re is already installed (current version is 1.9.0).
[NOTE] Package ANSITerminal is already installed (current version is 0.8.2).
[NOTE] Package ppx_deriving is already installed (current version is 5.2.1).
The following actions will be performed:
  ∗ install mlgmpidl 1.2.13
Do you want to continue? [Y/n] y

<><> Gathering sources ><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[mlgmpidl.1.2.13] found in cache

<><> Processing actions <><><><><><><><><><><><><><><><><><><><><><><><><><><><>
[ERROR] The compilation of mlgmpidl failed at
        "/home/jbarnes01/.opam/opam-init/hooks/sandbox.sh build make".

#=== ERROR while compiling mlgmpidl.1.2.13 ====================================#
\# context     2.0.7 | linux/x86_64 | ocaml-option-flambda.1 ocaml-option-musl.1 ocaml-option-static.1 ocaml-variants.4.12.0+options | https://opam.ocaml.org/#fde0c1b5
\# path        ~/.opam/4.12.0+flambda+static/.opam-switch/build/mlgmpidl.1.2.13
\# command     ~/.opam/opam-init/hooks/sandbox.sh build make
\# exit-code   2
\# env-file    ~/.opam/log/mlgmpidl-23952-6d07ae.env
\# output-file ~/.opam/log/mlgmpidl-23952-6d07ae.out
\### output ###
\# [...]
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlc -package "bigarray" -annot -g -c gmp_random.ml
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlc -package "bigarray" -annot -g -c mpzf.ml
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlc -package "bigarray" -annot -g -c mpqf.ml
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlc -package "bigarray" -annot -g -c mpfrf.ml
\# /home/jbarnes01/.opam/4.12.0+flambda+static/bin/ocamlfind ocamlopt -package "bigarray" -ccopt -U__STRICT_ANSI__ -ccopt -UNDEBUG -ccopt -O0 -ccopt -g -ccopt -Wcast-qual -ccopt -Wswitch -ccopt -Wall -ccopt -Wextra -ccopt -Wundef -ccopt -Wcast-align -ccopt -Wno-unused -ccopt -Wno-unused-parameter -ccopt -Wno-unused-function -ccopt -fPIC -ccopt -Werror-implicit-function-declaration -ccopt -Wbad-f[...]
\# In file included from mpz_caml.c:21:0:
\# gmp_caml.h:15:10: fatal error: gmp.h: Aucun fichier ou dossier de ce type
\#  #include "gmp.h"
\#           ^~~~~~~
\# compilation terminated.
\# Makefile:273: recipe for target 'mpz_caml.o' failed
\# make: *** [mpz_caml.o] Error 2

<><> Error report <><><><><><><><><><><><><><><><><><><><><><><><><><><><><><><>
┌─ The following actions failed
│ λ build mlgmpidl 1.2.13
└─ 
╶─ No changes have been performed
Makefile:63: recipe for target 'deps' failed
make: *** [deps] Error 31

edit: correct markdown formatting for lines starting with #

**Comment by rmonat** [comment]
You probably need something like `libgmp-dev` installed through your package manager. `opam` might be able to find them using `opam install depext` and then `opam depext px_deriving ANSITerminal re ocamlgraph dune menhir cmdliner dune-build-info visitors parmap num ocamlformat mlgmpidl ocamlformat`

**Comment by jemsab** [comment]
Hi Raphaël, I seem to already have the required packages. 
Also compilation works fine with a switch without musl and static :

 /home/jbarnes01/Projets/mlang$ **opam depext mlgmpidl**
\# Detecting depexts using vars: arch=x86_64, os=linux, os-distribution=ubuntu, os-family=debian
\# The following system packages are needed:
libgmp-dev
libmpfr-dev
perl
\# **All required OS packages found.**

/home/jbarnes01/Projets/mlang$ **sudo apt install libgmp-dev**
Reading package lists... Done
Building dependency tree       
Reading state information... Done
**libgmp-dev is already the newest version (2:6.1.2+dfsg-2).**

**Comment by rmonat** [comment]
That's strange but I'm able to reproduce on the same kind of switch (4.11.1+musl+static+flambda, 4.08.0+musl+static+flambda). I'm not really familiar with musl and static linking, and could not fix the issue at the source.

Maybe the best would be to leave an issue on mlgmpidl repo: https://github.com/nberth/mlgmpidl

In the meantime, I think this package is only used in `backend_ir/bir_number.ml`. If you disable all `NumberInterface` modules except `RegularFloatNumber`, you may be able to drop the dependency.

**Comment by denismerigoux** [comment]
Ok interesting, I hadn't thought of this limitation before. If there is a big need we can remove the dependency on `GMP` in the compiler or put it behind a configuration flag, since it is only used for running the interpreter with multi-precision arithmetic. That was useful for the research paper but not much so for production use I guess.

**Comment by denismerigoux** [comment]
What's the version of Ubuntu that you want to compiler Mlang on by the way ? Is it below 16.04 ?

**Comment by jemsab** [comment]
Hi Denis, it'll be on CentOS 7 with very limited packages (i.e. no bwrap to install opam even), which is why a completely static binary would seem to be a necessity.

**Comment by denismerigoux** [comment]
Ok I see. For the record you can push this issue as an argument for upgrading the OS from this 2009 distribution, but in the meantime yes a static binary will be necessary. Other workaround: if you have a machine with a newer distribution lying around, you can install Catala on it and compile the M and M++ files on them. Then you transfer the generated C files to the old CentOS machine and you compile the C there.

**Comment by jemsab** [comment]
Unfortunately CentOS 8 is effectively abandoned by the CentOS project at the end of the year so there is no clear upgrade path for those systems.

The problem is not the compilation itself (we have newer platforms we can use for compilation) but for M development and testing. So using *Catala* ;) on another platform won't help us in this case.

**Comment by jemsab** [comment]
Bug submitted to mlgmpidl:  https://github.com/nberth/mlgmpidl/issues/11

**Comment by jemsab** [comment]
The solution provided by here https://github.com/nberth/mlgmpidl/issues/11#issuecomment-884881150 definitely works and has allowed me to compile a static binary of Mlang with no dependencies whatsoever. A small modification has to be made to the root dune file so as to add the following ocamlopt flag : "-ccopt -static". 

If I can find a way to pass options to dune from the command line I will create a pull request to allow static compilation, as if this option is hard coded then everyone will need musl and statically compiled gmp and mpfr.

The solution seems to work in OCaml switches 4.11.x and prior. Linking files with an OCaml 4.12 switch fails with an error related to symbol relocation relaxing.
