### ISSUE TITLE
Modify input-out configuration system

### ISSUE THREAD

**Issue by jemsab** [MLanguage/mlang#20]
Modify input-out configuration system used by Mlang, based on the .m_spec files, so as to easily select the input/outputs expected by the C source files of higher layers of DGFiP code (INTER files).

Add keywords to allow adding arbitrary number of variables, for exemple : allow all available inputs or all variables with `cotsoc` is 1

**Comment by jemsab** [comment]
Reentrant variables that are typed returnable (`restituee`) seem to also be typed `primrest = 1`and `base`. This may be the key to discriminating amongst them.

**Comment by jemsab** [comment]
Unfortunately that doesn't seem to be sufficient, I've isolated a couple of variables that are reentrant in the INTER files : PREM8_11 and AVFISCOP. I'm in touch with the team to see if we can sort something out.

As I understand it, these variables are reentrant but not available for external clients to be used which is why they have this special typing.

**Comment by denismerigoux** [comment]
![5k86bt](https://user-images.githubusercontent.com/1766128/130239516-4d5ef408-9a1c-4173-b204-e3ed575f015f.jpg)
