### ISSUE TITLE
Implement calculation anomaly handling

### ISSUE THREAD

**Issue by jemsab** [MLanguage/mlang#24]
Implement calculation anomaly handling as defined in the M code, with every level of anomaly.

Give a way to configure what happens for each anomaly level with C compilation flags (implement the same solution as the current DGFiP implementation).

**Comment by jemsab** [comment]
C compilation flags to configure error level should be done with the new backend in  #19

**Comment by jemsab** [comment]
Partially handled by PR #53 

Still needs testing

**Comment by jemsab** [comment]
Some clients also need to be able to configure max number of `discordance`s and `information` anomalies, another PR is necessary to add this functionality.

**Comment by jemsab** [comment]
After having investigated the code further, it seems that exiting after having reached a critical number of `discordance` or `information` anomalies are handled internally in INTER files. Apart from testing this issue can be closed for Sprint 1

**Comment by Keryan-dev** [comment]
IIRC only the Java and DGFIP C backend implements this for now, the latter being extensively tested. I think this is closed, the remaining work can be listed as another issue (namely, #177).
