### ISSUE TITLE
Connect Mlang generated code with current DGFiP tax engine

### ISSUE THREAD

**Issue by jemsab** [MLanguage/mlang#25]
Connect Mlang generated code C code with current DGFiP tax engine with the upper layers of (INTER files) and polyfill all the functions expected by those layers (revenus.c, etc.).

**Comment by Keryan-dev** [comment]
I'll reopen this for now, since #18 isn't closed yet and the job is not entirely done. We still miss chains functions for INTER files.

**Comment by Keryan-dev** [comment]
Reclosing it. Definitely done.
