### ISSUE TITLE
Slice back-end code in functions corresponding to M rules

### ISSUE THREAD

**Issue by Keryan-dev** [MLanguage/mlang#26]
This is the first item of issue #22, which deserve its own issue I think.

The goal is to generate functions that reflect the rules of input M specs.
Since this will have a negative impact on performance due to the restrictions on optimisation passes, it should have its own compilation flags.

**Comment by Keryan-dev** [comment]
I can't assign myself to an issue (yet ?), so I do so verbally here.

**Comment by denismerigoux** [comment]
Hi Keryan, thanks for creating the issue. I'm not sure will have a negative impact on performance, what restrictions on the optimisation passes do you think it will create ? For me, this will just transform `type program = stmt list` into `type program = rule list` where `type rule = stmt list`, no ?

**Comment by Keryan-dev** [comment]
> I'm not sure will have a negative impact on performance, what restrictions on the optimisation passes do you think it will create ? For me, this will just transform `type program = stmt list` into `type program = rule list` where `type rule = stmt list`, no ?

That's the plan, yes. You know the optimisation passes better than I do, but I was under the impression that it takes advantage of the fact that all the statements of a program are grouped together to optimise a lot through reordering (among other things), which would not be possible if statements are spread around in small blocks of codes that can only be optimised separately.

**Comment by denismerigoux** [comment]
Closed by #55
