### ISSUE TITLE
Modify C backend - Evaluation & testing

### ISSUE THREAD

**Issue by jemsab** [MLanguage/mlang#29]
The final objective is that the code generated by Mlang with the DGFiP specific C backend is connected to upper layers of the current C sources (INTER files) so that they can be compiled by the DGFiP's makefiles and therefore produce a binary that can pass their tests (around 1000) for the tax year 2020 (Income earned in 2020 and tax calculated over the summer of 2021).

Concerning the test infrastructure, several things must be considered : 

We'll need to keep the current DGFiP test infrastructure ("autotests"), with the AIF/AIT binaries keeping their current output.

In order to run things in a CI environment, Raphaël and Denis created an independent test infrastructure in examples/c/backend_test with a parser that reads DGFiP test files and runs the tax calculator, comparing expected results  and exiting with an error code in case of discrepancy. This test framework currently runs using Mlang's C backend.

Some decisions have to be made: either sort out the current DGFiP test framework and have it run under a CI environment soon or convert the current test framework in Mlang to use the new DGFiP specific C backend.

**Comment by jemsab** [comment]
@denismerigoux concerning the possibility, could you explain with the tests are currently run on Gitlab rather than here on Github, was there some technical difficulty you encountered?

**Comment by denismerigoux** [comment]
@rmonat can explain it when he'll be back from vacations, but basically his university (Paris VI) has dedicated CI accessible from gitlab.com, so we figured we would use that instead of GitHub Actions.

**Comment by denismerigoux** [comment]
More explanations : the machine on which the CI runs from this repo (https://gitlab.com/rmonat/mlang) is a machinne physically located in Raphaël's laboratory. It has 48 cores and 256 GB of RAM, which is handy because to compile the C we currently need ~10 GB of RAM and running 488 tests in parallel goes faster with the interpreter.

**Comment by jemsab** [comment]
I see! Although I would imagine that once Raphaël finishes his degree then access to that machine will become somewhat limited?

**Comment by denismerigoux** [comment]
Raphaël will stay at his lab until September 2022 so we have some time to think about alternatives :) However putting a link in the README as to where we can see the results of the CI would be good.

**Comment by jemsab** [comment]
Isn't that what the "pipeline: passed" at the top of the README means?

**Comment by denismerigoux** [comment]
Indeed, it should be good then

**Comment by rmonat** [comment]
So, we used the Gitlab CI because we already had a machine configured to run the Gitlab CI clients at the lab. 
I confirm I should be able to maintain this until September 2022 indeed.

**Comment by jemsab** [comment]
Well that's great news! 

As I mentioned in #16 I think producing regular builds in a CI environment would simplify deployment on DGFiP infrastructure, especially now that static builds seem to work.

This is probably an issue by itself but I wonder if we should keep tests and builds in the same place and then move everything sometime next year or if we should have builds already working on Github and then move tests when the time comes.
