### ISSUE TITLE
Changes around CI

### ISSUE THREAD

**Issue by jemsab** [MLanguage/mlang#52]
In order to centralize conversations around our CI workflow, I've created this issue.

Currently CI is handled by a Gitlab runner hosted by @rmonat 's university. As I understand it we should have use of that platform for another year. After that time a new solution must be found.

Previous attempts to use Github actions weren't successful because of the service's limitations. 

In browsing Github's T&Cs I see no limit on time usage for actions in public repositories, only the limit of 6 hours per job and 72 hours per workflow. That should be plenty for our needs. 

The only other limit I can find is that the hardware for Linux runners has 7GB of RAM. 

@denismerigoux or @rmonat could you confirm that it was indeed the RAM limit that was being hit ? Or is there another limitation I haven't found ?

**Comment by rmonat** [comment]
I confirm that Gitlab's CI should run on our servers for one more year. If you have a server on which Gitlab or Github runners can be installed and run, the transition shouldn't be too difficult.

I remember the resource bounds on Github actions to be more restrictive, this might have changed since we last tried. I think 7GB ram is too low to test the C backend (if I remember correctly, LLVM takes up to 10GB of ram to compile the code).

**Comment by jemsab** [comment]
> I confirm that Gitlab's CI should run on our servers for one more year. If you have a server on which Gitlab or Github runners can be installed and run, the transition shouldn't be too difficult.
> 
 Unfortunately we don't have anything accessible from the internet at the moment.
> 
> I remember the resource bounds on Github actions to be more restrictive, this might have changed since we last tried. I think 7GB ram is too low to test the C backend (if I remember correctly, LLVM takes up to 10GB of ram to compile the code).
> 
Indeed although the current work on splitting the c backends into a function per M rule should decrease compile time and ram usage. 

If you don't mind I would like to produce static builds as part of the CI pipeline, so that we just have to download and use them. 

It might make more sense to build on GitHub to have all the code, workflow (ex tests) and builds in the same place. 

Do you mind if I add some stuff to the GitHub workflow in order to make that happen? Unless you feel the builds should also be on Gitlab ?

**Comment by rmonat** [comment]
> Unfortunately we don't have anything accessible from the internet at the moment.

I guess it would be interesting to have a server like that but there's still time to think about it.

> Indeed although the current work on splitting the c backends into a function per M rule should decrease compile time and ram usage.

Yes, I guess this should enable using Github actions

> If you don't mind I would like to produce static builds as part of the CI pipeline, so that we just have to download and use them.
> It might make more sense to build on GitHub to have all the code, workflow (ex tests) and builds in the same place.
> Do you mind if I add some stuff to the GitHub workflow in order to make that happen? Unless you feel the builds should also be on Gitlab ?

No problem! Actually, the CI already keeps mlang's binary ([example](https://gitlab.com/rmonat/mlang/-/jobs/1489456069/artifacts/browse), [ci code](https://gitlab.com/rmonat/mlang/-/blob/master/.gitlab-ci.yml#L22)).

**Comment by jemsab** [comment]
Possible optimization : https://github.com/ocurrent/ocaml-ci

**Comment by Keryan-dev** [comment]
Closing, the current state of generated code allows the entire CI tu run on Github for a while now.
Should the question be raised again later, it would be another issue.
