### ISSUE TITLE
DGFIP C compilation flags in dgfip backend test

### ISSUE THREAD

**Issue by Keryan-dev** [MLanguage/mlang#73]
We need to make sure the generated C code will compile in the DGFIP environment if it does in local tests, e.g. add C89 constraints.

**Comment by Keryan-dev** [comment]
We did compile and run it in the DGFIP environment, but I'm not sure it is reflected on CI tests. Or if we can at all actually. @ddeclerck ?

**Comment by ddeclerck** [comment]
As far as I remember, I tweaked the code to make it as C89-friendly as possible, but there might still be some bits of C99 or GNU extensions... I have to check exactly.

**Comment by Keryan-dev** [comment]
Ideally, we could have compile options on the CI that reflects the constraints of production environment to avoid "but it works on our machine" problems, whatever the exact configuration.
I recall their C compiler is not exactly C89 either so it might just not be possible to emulate those constraints. In which case we can assume what's already there is good enough.

**Comment by ddeclerck** [comment]
Just checked, it compiles fine with `std=c89`. Just a few minor warnings with `-pedantic` ; I'll sort them out, by precaution.

**Comment by ddeclerck** [comment]
That has been done. PR #191 should address these concerns.
