### ISSUE TITLE
GitHub Actions failing based on inexistant mli files

### ISSUE THREAD

**Issue by jemsab** [MLanguage/mlang#90]
The following build failed because of changes in the master branch that haven't yet been merged into my PR : https://github.com/MLanguage/mlang/runs/4094455924?check_suite_focus=true

The mir.mli file does not exist in my branch, yet appears to block the CI pipeline for this PR. 

After having investigated with @Keryan-dev, the problem appears to be with the actions/checkout@v2 stage.
In the logs, we can see that during `Checking out the ref`, there is a merge of master into the branch before other stages are ran with this line : 
``` 
 HEAD is now at a5835d4 Merge 66bd019a29c26db15442369274d600dcdd107eb2 into 8d43a4633d265e5cb63a9cdd452377dcde04f998
474
```
I don't think there is any action on our side we just need to be aware of this implicit merge, any CI action is necessarily run on the master-merged version of a PR

**Comment by jemsab** [comment]
After searching further in the Github docs, it appears this is an option that may be disabled : https://github.com/actions/checkout#checkout-pull-request-head-commit-instead-of-merge-commit

The question is: do we want to? It seems to me that once we are aware of this, it is not a bad design decision and that mergability of PRs is something that we want to test.

**Comment by denismerigoux** [comment]
I think we want the CI to run on a merged version of the branch, because your branch should preferably always be in sync with `master`. Hence I close this issue, because the behavior you observed is rather a reminder to merge `master` into your PR branch that an actual bug.
